### PR TITLE
add gvm use -n/--no-install option

### PR DESCRIPTION
**Pull request by graphaelli**
Mostly to enable `gvm use tip -n`.

```
[15:02:09] ~/src/gvm (use-no-install) $ cat ~/.gvm/cache/go.meta 
{"Updated":"2021-01-07T14:23:47.883139-05:00"}

[15:02:15] ~/src/gvm (use-no-install) $ gvm use tip -n
export GOROOT="/Users/gil/.gvm/versions/gotip.darwin.amd64"
export PATH="/Users/gil/.gvm/versions/gotip.darwin.amd64/bin:$PATH"

[15:02:18] ~/src/gvm (use-no-install) $ cat ~/.gvm/cache/go.meta 
{"Updated":"2021-01-07T14:23:47.883139-05:00"}

[15:02:19] ~/src/gvm (use-no-install) $ gvm use tip
export GOROOT="/Users/gil/.gvm/versions/gotip.darwin.amd64"
export PATH="/Users/gil/.gvm/versions/gotip.darwin.amd64/bin:$PATH"

[15:03:11] ~/src/gvm (use-no-install) $ cat ~/.gvm/cache/go.meta 
{"Updated":"2021-01-08T15:02:23.408087-05:00"}
```

### CODE REVIEW

**Comment by andrewkroh** [comment]
Hi Gil, so is this to enable the use of `gvm use tip` without having it do an update?

**Comment by graphaelli** [comment]
Yes, exactly

**Review by andrewkroh — APPROVED** [review]
LGTM

**Comment by andrewkroh** [comment]
I'll add a changelog entry and make a release.

**Pull request merged**
